.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

add issue template and pull request template
See templates when creating a pull request or issue

docs(github): add issue template andd pull request template

---

dags/ods/google_search_console/dag.py
dags/ods/google_search_console/udfs/google_search.py

看來是之前 black 和 isort 的版號更新了，但我 local 還是舊的
所以我 format 完之後跟 CI 跑出來的不一樣就 fail 了XD

style(lint): update my black and isort to pass CI

---

dags/ods/google_search_console/udfs/google_search.py

chore(wording): revamp some wordings

---

dags/app/channel_reminder/dag.py

:speech_balloon: (discord reminder) update wording

---

README.md

docs(README): update for more precise description

---

dags/app/channel_reminder/dag.py

just update the link of Hackmd

:sparkles: (dags) update link of hackmd

---

README.md

refer to this article for naming convention

:pencil: (readme)

---

contrib/upload-kktix-ticket-csv-to-bigquery.py

- **Bugfix**
- **Other (unittest)**
I got a lot of useful suggestion from this pull request https://github.com/pycontw/PyCon-ETL/pull/34 . This pull request applies lesson learned from the previous pull request https://github.com/pycontw/PyCon-ETL/pull/34 .
`python -m unittest upload-kktix-ticket-csv-to-bigquery.py`
All unittest should pass.

test(contrib): upload-kktix-ticket-csv-to-bigquery.py: refactor Test2020Ticket

---

contrib/upload-kktix-ticket-csv-to-bigquery.sh

Snapshot the wrapper command used to upload the data.
1. export GOOGLE_APPLICATION_CREDENTIALS="<where to access service-account.json>"
2. invoke the shell script
New tables are created in BigQuery.
https://github.com/pycontw/PyCon-ETL/issues/5

feat(contrib): batch upload kktix tickets

---

.env.sh

my bad, accidentally committed webhook to github...

remove webhook

---

dags/ods/youtube/dags/dag.py
dags/ods/youtube/sqls/create_table.sql
dags/ods/youtube/udfs/youtube_api.py

insert viewCount, likecount etc into BQ
too lazy to add test case 😓 
1. follow readme to kick off a job on your local
2. go to bq and you should see incoming data
ditto
<https://hackmd.io/54uxwADjSNaeDDMsdXOp3g>

:sparkles: (youtube) insert view count into youtube

---

contrib/survey_cake/udfs/survey_cake_csv_uploader.py
contrib/upload-kktix-ticket-csv-to-bigquery.py

1. the load job to append the data to the table and allowing nullable field addition.
2. update mapping table for  2021 kktix data.

feat: modify job_config & update mapping table

---

contrib/README.md
contrib/survey_cake/udfs/survey_cake_csv_uploader.py

- **Bugfix**
refer to [suverykcake's readme](https://github.com/pycontw/pycon-etl/blob/47e65cb781bb7f70ddc1c73fe8a7278dfc639407/contrib/README.md)
example dashboard
<https://metabase.pycon.tw/question/70>

:bug: (surveycake) filter out existing question id

---

README.md

- **Bugfix**
- **Breaking change** (any change that would cause existing functionality to not work as expected)

<doc/docker>: remove --rm flag

---

README.md

1. add windows os version command
2. revised "Would need to setup Snowflake Connection manually, find @DavidTnfsh if you don't have those secrets" to "Find @DavidTnfsh if you don't have those secrets"
N/A
N/A
N/A
N/A

add windows os version command

---

.gitignore
README.md
dags/ods/kktix_ticket_orders/discord_team_registration_bot_dag.py
dags/ods/kktix_ticket_orders/kktix_dag.py
dags/ods/kktix_ticket_orders/udfs/kktix_api.py

chores, setup the backfill logic

<config>(kktix): split 1 big dag into 2 dags

---

dags/ods/kktix_ticket_orders/udfs/discord_bot.py

update wording for discord bot msg

<chores>(discord): updated wording

---

dags/ods/kktix_ticket_orders/udfs/discord_bot.py

updated msg format per feedback~

<refactor>(kktix): reformat our discord msg

---

dags/ods/kktix_ticket_orders/udfs/discord_bot.py

<format>: added metabase link

---

dags/ods/youtube/udfs/youtube_api.py

- **Bugfix**
handled youtube payload's edge case

<fix>(youtube): catch videoId exception

---

dags/ods/kktix_ticket_orders/udfs/discord_bot.py

per feedback, sorted these ticket name for readness!
https://discord.com/channels/752904426057892052/999503809736867860/1002366677117321318
https://discord.com/channels/752904426057892052/999503809736867860/1002366677117321318

<feat>(discord): sorted msg for comparison

---

dags/ods/kktix_ticket_orders/udfs/discord_bot.py

<fix>(discord): only 1 item in array had an extra comma

---

dags/ods/kktix_ticket_orders/udfs/discord_bot.py

- **Bugfix**
- **Breaking change** (any change that would cause existing functionality to not work as expected)

:bug: (sql)

---

dags/ods/kktix_ticket_orders/kktix_dag.py
dags/ods/kktix_ticket_orders/udfs/discord_bot.py
dags/ods/kktix_ticket_orders/udfs/gather_town_loader.py
dags/ods/kktix_ticket_orders/udfs/kktix_api.py
dags/ods/kktix_ticket_orders/udfs/kktix_transformer.py

Once user bought a ticket on KKTIX, Airflow would ingest these data every 5 mins and whitelist his/her email into gathertown automatically
this PR doesn't handle the edge case, which is users refund their ticket but still keep his/her gathertown login permission. We can punt on this for now until wrapping up all the necessities for Conference.
cc @henry410213028 @GeekAngus 
TBD 
should see your nickname after logging into Gathertown, however right now you can only see `anonymous`
https://hackmd.io/PM_sWO5USo6dxMqT1uCrCQ?view#Solution and check `gather town section`

<feat>(kktix): added gather town whitelist feature

---

dags/ods/kktix_ticket_orders/udfs/kktix_api.py

- **Bugfix**
cc @henry410213028 
seems to me that klaviyo module has been failing for 3 days. My hunch is that there's some mis config on Klaviyo admin page

:ambulance: (klaviyo) comment klaviyo for now

---

dags/ods/kktix_ticket_orders/udfs/gather_town_loader.py

:bug: (gathertown) wrong slice'

---

dags/ods/kktix_ticket_orders/klaviyo_backfill_dag.py
dags/ods/kktix_ticket_orders/udfs/batch_kktix2mailer.py
dags/ods/kktix_ticket_orders/udfs/kktix_api.py
poetry.lock
pyproject.toml

- **Other**
To prevent send duplicated mail, change schedule time to hourly

hotfix: change mailer schedule interval from daily to hourly

---

dags/ods/kktix_ticket_orders/udfs/bigquery_loader.py

:bug: (kktix) dedupe bq records in case we backfill

---

README.md
dags/ods/kktix_ticket_orders/udfs/batch_kktix2mailer.py
dags/ods/kktix_ticket_orders/udfs/kktix_api.py

hide KKTIX's url path to keep @gtbcoding 's secret
https://discord.com/channels/752904426057892052/900721883383758879/1016745608935120956

:lock: (kktix) store kktix api into Variable

---

contrib/survey_cake/upload-survey-cake-csv-to-bigquery.py

:pencil: (cli) print out hint msg

---

contrib/upload-kktix-ticket-csv-to-bigquery.py

- **Bugfix**
2022's data format differs with 2021's, so I wrote some dirty code to tackle them.
Theoretically, we'll deprecate this script and in favor of @gtbcoding 's KKTIX 's as new data source. But still keep this script as a backup plan.

:bug: (kktix-uploader) handled edge cases

---

.github/workflows/python.yml

nothing, just a precaution to prevent running out of action quota

[ci]: set up time-limit in case out of quota

---

dags/app/channel_reminder/dag.py
dags/app/channel_reminder/udfs/discord.py

https://discord.com/channels/752904426057892052/991161848122576896/1069181793531592715

:sparkles: (discord) add new reminder

---

dags/app/proposal_reminder/dag.py
dags/app/proposal_reminder/udf.py

* add new dag for send program proposal summary to discord
- [v] Add test cases to all the changes you introduce
- [v] Run `poetry run pytest` locally to ensure all linter checks pass
- [v] Update the documentation if necessary

feat(app): add program proposal discord reminder

---

dags/app/proposal_reminder/dag.py

- Change talk reminder dag config
Proposal deadline is coming, talk team pay more attention on proposal summary.
- [ v ] Add test cases to all the changes you introduce
- [ v ] Run `poetry run pytest` locally to ensure all linter checks pass
- [ v ] Update the documentation if necessary

increase program talk notify frequency

---

dags/ods/kktix_ticket_orders/kktix_dag.py

since my janky implementation, it really takes time for the dag to catch up. Use this workaround to accelerate the extraction

[chores]: update start date to accelerate the extraction

---

dags/ods/kktix_ticket_orders/udfs/discord_bot.py

- **Bugfix**
Rewrite bigquery sql statement, remove duplicated records
- [v] Add test cases to all the changes you introduce
- [v] Run `poetry run pytest` locally to ensure all linter checks pass
- [v] Update the documentation if necessary

fix(ods): wrong kktix order stats

---

dags/app/channel_reminder/dag.py
dags/app/team_registration_bot/dag.py
dags/app/team_registration_bot/udf.py

- fix wrong module name
- calculate ticket total income
- [v] Add test cases to all the changes you introduce
- [v] Run `poetry run pytest` locally to ensure all linter checks pass
- [v] Update the documentation if necessary

Feat ticket income

---

dags/ods/kktix_ticket_orders/kktix_dag.py
dags/ods/kktix_ticket_orders/udfs/kktix_api.py

- **Bugfix**
增加排程間隔, 避免執行大量短任務, 造成服務阻塞
- [v] Add test cases to all the changes you introduce
- [v] Run `poetry run pytest` locally to ensure all linter checks pass
- [v] Update the documentation if necessary

fix(ods): increase kktix dag schedule intraval

---

dags/app/twitter_post_notification_bot/dag.py
dags/app/twitter_post_notification_bot/udf.py

For the sake of saving money, we're going to use `RapidAPI` to send twitter post noti into discord

[feat](twitter): add twitter api into airflow

---

dags/app/finance_bot/dag.py

資料夾是finance_bot import忘了打bot
- **Bugfix**

fix udf import

---

dags/app/finance_bot/dag.py

fix task name

---

dags/app/finance_bot/udf.py

- **Bugfix**
fix variable to env variable

fix variable

---

.github/workflows/dockerimage.yml

- **Bugfix**
not sure why the CI for updating staging image is not working

:construction_worker: (docker) test it

---

dags/app/proposal_reminder/dag.py

Change the date range of call for proposal 2024

Change the date range of call for proposal 2024

---

dags/app/finance_bot/udf.py

switch test to ods

---

dags/ods/kktix_ticket_orders/kktix_dag.py
dags/ods/kktix_ticket_orders/kktix_refund_dag.py

- **Fix**
Create 2024 kktix-ticket DAGs

fix(ods): 2024 kktix-ticket

---

dags/ods/kktix_ticket_orders/udfs/bigquery_loader.py

- **Bugfix**
Fix sql script path

fix(ods): kktix script path

---

dags/ods/kktix_ticket_orders/udfs/bigquery_loader.py

- **Bugfix**
Fix sql script path

fix(ods): sql script path

---

dags/ods/kktix_ticket_orders/kktix_dag.py

Remove unused gather town task from kktix dag

fix(ods): remove unused gathertown task

---

dags/ods/fb_post_insights/udfs.py

fix message error

---

docker-compose.yml
docs/DEPLOYMENT.md

- **Bugfix**
Fix some deployment error

Fix deployment

---

dags/app/proposal_reminder/dag.py

- **Other**
Adjust the schedule and version of the proposal reminder DAG.

Call for proposal bot 2025

---

airflow.cfg

* refactor(airflow.cfg): remove the keys that we did not change the value
* feat(airflow.cfg): remove deprecated and used session_lifetime_days config

Remove default airflow cfg

---

Dockerfile
Dockerfile.test
dags/app/finance_bot/dag.py
dags/app/proposal_reminder/dag.py
dags/app/team_registration_bot/dag.py
dags/ods/kktix_ticket_orders/udfs/kktix_bq_dwd_etl.py
pyproject.toml
setup.cfg
uv.lock

* style(mypy): move mypy config from setup.cfg to pyproject.toml and add pandas stub
* build(docker): add airflow_home to python_path to allow customized module import
* refactor(dags): use absolute import path

Move mypy config from setup.cfg to pyproject.toml

---

airflow.cfg

Update airflow.cfg to decrease CPU loading

---

dags/airflow_log_cleanup.py
docker-compose-dev.yml
docker-compose.yml

Rewrite the huge bash script as separate airflow tasks

refactor(dags:airflow_log_cleanup): split the huge bash as separate tasks

---

airflow.cfg

- **Bugfix**
- **Breaking change** (any change that would cause existing functionality to not work as expected)

fix(airflow.cfg): fix duplicate core.max_active_tasks_per_dag

---

docker-compose-dev.yml
docker-compose.yml

Based on how we treat logs, we probably don't need to mount a local directory.

build(docker-compose): Create a volume instead of mount a local one for logs

---

dags/utils/posts_insights/linkedin.py

fix(posts_insights): fallback to empty list when no media resource received
